name: flutter_plugin_ble_printer
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  pigeon: 23.0.0
  get: ^4.6.6


  #  flutter_blue_plus: ^1.3.1
#  flutter_blue_plus:
#    path: /Users/liangjiqian/githubreps/flutter/flutter_blue_plus
#    git:
#      url: https://github.com/zero-li/flutter_blue_plus.git
#      ref: f06f8bcb9fd2ff4dcbd4ef501a7ce2cde46e13cb


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.zgo.flutter_plugin_ble_printer
        pluginClass: FlutterPluginBlePrinterPlugin
      ios:
        pluginClass: FlutterPluginBlePrinterPlugin

